#springboot的配置信息
server:
  port: 8080  #设置端口号
  context-path: /  #设置项目访问路径

spring:
  thymeleaf:
    cache: false  #修改模板不用重启服务器
  resources:
    # 设置静态资源访问路径
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/